sixpackapi:
  build: .
  command: "sixpack.server:start"
  environment:
    - SIXPACK_CONFIG_ENABLED=true
    - SIXPACK_CONFIG_REDIS_PORT=6379
    - SIXPACK_CONFIG_REDIS_HOST=http://hub-redis
    - SIXPACK_CONFIG_REDIS_PREFIX=sixpack
  ports:
   - "5000:8000"
sixpackweb:
  build: .
  command: "sixpack.web:start"
  environment:
    - SIXPACK_CONFIG_ENABLED=true
    - SIXPACK_CONFIG_REDIS_PORT=6379
    - SIXPACK_CONFIG_REDIS_HOST=http://hub-redis
    - SIXPACK_CONFIG_REDIS_PREFIX=sixpack
  ports:
   - "5001:8000"

